### ISSUE TITLE
Host images here or link to external servers?

### ISSUE THREAD

**Issue by T-Engel** [gbif/hp-land#3]
This is a question that came up yesterday, as I changed some of the photos: I used some free to use images from inaturalist. In that case, shall I download them and include them in the assets folder or is it okay to use the image link from iNaturalist, as I did. I guess both works, I was just wondering what is best practice. How do you do this for the virtual herbarium, @jholetschek ?

**Comment by jholetschek** [comment]
From what I see in the source code of the pages, GBIF caches the images while building the portal. So they should continue even if the original photo is gone. For this reason, I think just referencing the images via link is fine!

**Comment by MortenHofft** [comment]
I would add it to he assets folder, just to be sure. It will likely perform better and is guareteed to work.
I wouldn't rely on the GBIF image cache as a backup as it could be flushed. I'm not even sure if we have exceptions for e.g. inat images and how long we keep those in cache.

**Comment by T-Engel** [comment]
Thanks. I just added the images to our assets folder. https://github.com/gbif/hp-land/commit/8f4d27bacbe0478a7d6f87d3fe8a751a0d44c648
