### ISSUE TITLE
The return of the gallery tab

### ISSUE THREAD

**Issue by T-Engel** [gbif/hp-land#4]
I vote for including the gallery tab again. Especially, as we include citizen science observations such as iNaturalist this becomes very interesting. It's nice for users to see what the species looks like.
We don't have to implement it just  yet, but let's keep it in mind.
This seems to be the line that has to change:
https://github.com/gbif/hp-land/blob/cb1f9b3bf41fb0bdd6f66e9dac4a9bdcdf27e4cd/_includes/js/config.js#L34

**Comment by jholetschek** [comment]
Sure! I've removed this tab because right now there are no images - so I think it's confusing for the user to have that. But it's easy to turn it on again.

**Comment by T-Engel** [comment]
Great. I agree, it only makes sense to have it when there are images. So let's do it later!

**Comment by jholetschek** [comment]
I'd put it back where it was - in third place, after table view. The dataset doesn't show any record details, so I'd move it to the end (before or after Download).

**Comment by T-Engel** [comment]
Sounds good. I hadn't thought much about the position to be honest. Just changed it
