### ISSUE TITLE
Search for vernacular names?

### ISSUE THREAD

**Issue by jholetschek** [gbif/hp-land#5]
Since our portal will be used by many citizen scientists, we're wondering whether it's possible to include a search filter based on vernacular names? The GBIF backbone has quite a lot of common names, so using them in a filter would be great!

Apparently gbif.org doesn't have such a filter for the occurrence search, only for species: https://www.gbif.org/species/search?q=windr%C3%B6schen

**Comment by MortenHofft** [comment]
It makes perfect sense. But there isn't really have a good/simple way to do it. You kind of have to build it yourself.

If you have a checklist that you would like to use, then you could search that using something like

https://api.gbif.org/v1/species/search?q=windr%C3%B6schen&qField=VERNACULAR&datasetKey=d7dddbf4-2cf0-4f39-9b2a-bb099caae36c

And then find the backbone entry from that. And then use that taxonKey as the filter.

**Comment by MortenHofft** [comment]
I remember that https://github.com/VtEcostudies/VAL_GBIF_Wordpress/issues/12 and https://vcevaldev.wpengine.com/
so something related

**Comment by jholetschek** [comment]
So to make sure I understand right: If we do that on our own (like the Vermont Atlas), it wouldn't appear within the occurrence widget as a regular filter, right?

The question on the checklist is something for @T-Engel . As far as I know, for now the GBIF backbone would be sufficient.

**Comment by T-Engel** [comment]
Thanks, Morten.  Yes, I think the GBIF backbone is a good starting point for our purpose because we have a rather broad taxonomic scope. I agree that the common names may cause some issues with synonyms and so on but nonetheless I think it's a useful addition- and it would not replace the search for scientific name. Basically, we would love to have the GBIF species search integrated in the occurrence search of the portal.

**Comment by MortenHofft** [comment]
> So to make sure I understand right: If we do that on our own (like the Vermont Atlas), it wouldn't appear within the occurrence widget as a regular filter, right?

All the suggest endpoints can be overwritten. So if you had an endpoint that allowed search by vernacular names and matched those to GBIF taxonKeys then that would work.
Example from the Vermont group where the "administrative area" filter suggest is overwritten
live example: https://vcevaldev.wpengine.com/gbif-explorer/
code: https://github.com/VtEcostudies/VAL_GBIF_Wordpress/blob/main/js/gbif_data_widget.js#L39 and https://github.com/VtEcostudies/VAL_GBIF_Wordpress/blob/main/js/gbif_data_widget.js#L65

To make it easier I've added a [new experimental suggest endpoint in the graphql service](https://graphql.gbif-staging.org/graphql?query=query%7B%0A%20%20taxonSuggestions%28%20q%3A%20%22windr%C3%B6schen%22%2C%20language%3A%20deu%2C%20vernacularNamesOnly%3A%20false%2C%20preferAccepted%3A%20true%2C%20strictMatching%3A%20false%29%20%7B%0A%20%20%20%20key%0A%20%20%20%20scientificName%0A%20%20%20%20vernacularName%0A%20%20%20%20taxonomicStatus%0A%20%20%20%20acceptedNameOf%0A%20%20%20%20classification%20%7B%0A%20%20%20%20%20%20name%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A) that perhaps do what you need

Also to make it simpler [I've added a suggest for it](https://github.com/gbif/gbif-web/commit/aee2804f5acf1acb747fb9c4566feaeb4b94e0d4#diff-7da790df0a729a129e2c2b81c703f4901676cb149353f324789750b049cbf43dR367)

So now it can be used by specifying that the filter should use the new suggest endpoint.

**Comment by MortenHofft** [comment]
That file is just because they split the gadm ID into a seperate file. It coudl just as well have been entered directly in 
https://github.com/VtEcostudies/VAL_GBIF_Wordpress/blob/main/js/gbif_data_widget.js#L44

So for you it would be `DEU`

```javascript
function getSuggestions({ client }) {
  return {
    gadmGid: {
      getSuggestions: ({ q }) => {
        const { promise, cancel } = client.v1Get(`/geocode/gadm/search?gadmGid=DEU&limit=100&q=${q}`); // this gadmGid=DEU is the new part, that means that the suggester will now only suggest things in Germany
        return {
          promise: promise.then(response => {
            return {
              data: response.data.results.map(x => ({ title: x.name, key: x.id, ...x }))
            }
          }),
          cancel
        }
      }
    }
  }
}
```

**Comment by MortenHofft** [comment]
I've added the restricted suggestions for gadm https://github.com/gbif/hp-land/commit/1ba22405310fffff4718ab5e0f0eeb455e564567. It should be easy to remove if you do not like it. Let me know if you would rather add these things yourself instead of me pushing changes.

**Comment by jholetschek** [comment]
Thanks, Morten! That's fine - that's what staging is for :)

One question on the suggestions for the common names: How would we allow a pattern search like in the other filter? So that the first suggestions show up after typing "windr", for example?

**Comment by T-Engel** [comment]
Yes, thanks going ahead with the gadm. The filter for Germany seems to work, however now it only suggests the 16 federal states and no smaller entities like counties or cities (it used to do that). Is that something you could include for us as well?

**Comment by MortenHofft** [comment]
@jholetschek 

> One question on the suggestions for the common names: How would we allow a pattern search like in the other filter? So that the first suggestions show up after typing "windr", for example?

That isn't possible with this API. It is simply using the `species/search` endpoint that also search vernacular names. 
The `species/suggest` endpoint is fast and supports autocompletion. Search is slower and does not handle partial words well. You will have to choose or provide a suggest service by other means.

**Comment by T-Engel** [comment]
> If it does not do what you expect it to, then could you please provide an example that I can check. It sounds like an API or content issue.

Sure. Try searching for "Leipzig". Currently, we don't get suggestions for that. The screenshot below is from the virtual herbarium. It should look like that. 

![image](https://user-images.githubusercontent.com/37897372/217817394-9f87dd9f-1a81-4d22-8beb-9c8454b8858b.png)

**Comment by MortenHofft** [comment]
Thanks - I cannot see anything in the screenshot, but the example text works
https://api.gbif.org/v1/geocode/gadm/search?gadmGid=DEU&limit=100&q=Leipzig
vs
https://api.gbif.org/v1/geocode/gadm/search?limit=100&q=Leipzig

**Comment by T-Engel** [comment]
Sorry for the small image. here comes a bigger one:

![image](https://user-images.githubusercontent.com/37897372/217818861-e1fd53eb-5d20-4f65-ad68-65ca1e27068e.png)

When I do the same for the LAND portal I get no suggestions.

**Comment by MortenHofft** [comment]
Thanks @T-Engel I've created an issue for it here https://github.com/gbif/geocode/issues/19 there seem to be a bug in the API

**Comment by T-Engel** [comment]
Great. Thanks!

**Comment by T-Engel** [comment]
@jholetschek, I guess we should make a decision regarding the administrative areas. Until the bug is fixed, I think it would be better to remove the Germany filter. I prefer keeping the smaller administrave areas, even if that means we get suggestions outside germany. What do you think?

**Comment by jholetschek** [comment]
Agreed, I'd also remove the filter on Germany.

**Comment by T-Engel** [comment]
Done.
