### ISSUE TITLE
Possibly rename filter

### ISSUE THREAD

**Issue by MortenHofft** [gbif/hp-land#6]
If you go with the suggest that includes vernacular names you might want to rename the filter from scientific name to something more easily understandable. Like "Species or group" instead of "Scientific name".

You can overwrite translations like this
```javascript
var siteConfig = {
  messages: {
    "filters.taxonKey.name": "Species or group",
    "filters.taxonKey.count": "{num, plural, one {species or group} other {# species or groups}}"
  },
  ...
}
```

and then make sure to overwrite it differntly per lanuage of course
https://github.com/gbif/hp-land/blob/master/_includes/js/config.js#L114

**Comment by T-Engel** [comment]
@jholetschek 
How do you feel about "Species " (EN) and "Art" (D)?

**Comment by jholetschek** [comment]
That's a taxon filter, which can be at any level, e.g. also a family: https://land.hp.gbif-staging.org/occurrence/search/?taxonKey=3925. So "taxon" or any other synonym would be better. Or "taxon name"?

**Comment by T-Engel** [comment]
You're right. But I doubt that many laypeople understand the term "taxon", whereas most people have heard of species I think. How about we mention both? "Species /Taxonomic group", "Art/ Taxonomische Gruppe"

**Comment by jholetschek** [comment]
Yes, that's an option.
Let's ask the group om pur meeting this afternoon!

**Comment by jholetschek** [comment]
Done. You forgot to insert a comma before this block - a classic.
