### ISSUE TITLE
add examples for how to change maps

### ISSUE THREAD

**Issue by MortenHofft** [gbif/hp-land#7]

**Comment by MortenHofft** [comment]
Add API keys
https://github.com/gbif/hp-land/commit/9cf9527e10097400be995ecd048d81d310146d9d

Add custom map layers
https://github.com/gbif/hp-land/commit/af1a65e51e19401e6f3b7a8ffdea1481cf0765a2
Zoom in to Venezuela to see layer for specific zoom level
USA shows wms source with geolayers
Europe shows geojson layer
hillshading is everywhere with mountains

NB: this is just examples of me pulling in data from random sources. You should check which services require you to pay!

**Comment by jholetschek** [comment]
Wow! ❤️❤️❤️
Thanks, Morten!

**Comment by MortenHofft** [comment]
Your change works. But it remembers your last use. So if you changed the map to bright and zoomed into denmark. Then it would show that despite refreshing. If you open this in a new private tab it will be NATURAL. And for new users it will show as NATURAL as well.
